### ISSUE TITLE
Laboratory Cutting and Coring

### ISSUE THREAD

**Issue by cisnerosjessica** [smithdavedesign/LTS-Public-#56]
The mix design samples are appearing in the Pre Cut ID only when I select the Gyratory Bulk in the Specimen Produced Type. From the gyratory compaction log, I input the mix design samples as As-Is samples. May we change this so the Produced ID Specimen for mix designs does not include the word "Bulk"? @RongzongWu

**Comment by RongzongWu** [comment]
fixed now. Please try again.

**Comment by cisnerosjessica** [comment]
Still does not work.
![Uploading Screenshot (1).png…]()

**Comment by RongzongWu** [comment]
Sorry, forgot to update the server. Now it should work.
